[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[profile.release-with-debug]
inherits = "release"
debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
fxhash = "0.2.1"
num-format = "0.4.4"